task: gemma_bbh_penguins_in_a_table
dataset_path: lukaemon/bbh
dataset_name: penguins_in_a_table
include: _gemma_bbh_template.yaml
doc_to_text: |
  {{input}}
  
  Put your answer in <answer>X</answer> where X is your answer letter (e.g., (A), (B), (C)).
filter_list:
  - name: "xml-strict-match"
    filter:
      - function: "regex"
        regex_pattern: "<answer>([\\s\\S]*?)</answer>"
      - function: "regex"
        group_select: -1
        regex_pattern: "\\([A-Z]\\)"
      - function: "take_first"
  - name: "xml-match"
    filter:
      - function: "regex"
        regex_pattern: "<answer>([\\s\\S]*)"
      - function: "regex"
        group_select: -1
        regex_pattern: "\\([A-Z]\\)"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "\\([A-Z]\\)"
      - function: "take_first"
